### PR TITLE
Update to latest VR

### PR DESCRIPTION
**Pull request by jwarwick-r7**
Pull in support for `+` in usernames.

### CODE REVIEW

**Comment by scudette** [comment]
Ah sorry - I already synced upstream in #14

This one is probably not necessary now

**Comment by jwarwick-r7** [comment]
Does this one have the fix to plus signs in usernames?

**Comment by jwarwick-r7** [comment]
I was hoping to update to the this release: https://github.com/Velocidex/velociraptor/commit/e1a8aba52fab0f46a43fc922be96da505c64bcec

**Comment by scudette** [comment]
Ah sorry of course. I just saw it was not rebased. Do you want to rebase it or open a new one?

**Comment by scudette** [comment]
I synced in another PR #16

**Pull request closed without merging**
